src/Entity/Review.php
<?php

namespace App\Entity;

use App\Repository\ReviewRepository;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ReviewRepository::class)
 */
class Review
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $title;

    /**
     * @ORM\Column(type="text")
     */
    private string $text;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="review", orphanRemoval=true)
     */
    private Collection $comments;

    /**
     * @ORM\Column(type="datetime")
     */
    private DateTimeInterface $date_create;

    /**
     * @ORM\Column(type="datetime")
     */
    private DateTimeInterface $date_update;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="reviews")
     * @ORM\JoinColumn(nullable=false)
     */
    private User $author;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="reviews")
     * @ORM\JoinColumn(nullable=false)
     */
    private Category $category;

    /**
     * @ORM\ManyToMany(targetEntity=Tag::class)
     */
    private Collection $tags;

    /**
     * @ORM\OneToMany(targetEntity=Like::class, mappedBy="review", orphanRemoval=true)
     */
    private Collection $likes;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="review", orphanRemoval=true)
     */
    private Collection $images;

    /**
     * @ORM\Column(type="smallint")
     * @Assert\Range(
     *      min = 0,
     *      max = 10,
     *      notInRangeMessage = "You must be between {{ min }} point and {{ max }} point tall to enter",
     * )
     */
    private int $score;

    /**
     * @ORM\OneToMany(targetEntity=Rating::class, mappedBy="review", orphanRemoval=true)
     */
    private Collection $ratings;

    public function __construct()
    {
        $this->setDateCreate(new \DateTime());
        $this->setDateUpdate(new \DateTime());
        $this->comments = new ArrayCollection();
        $this->tags = new ArrayCollection();
        $this->likes = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->ratings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(bool $raw = false): string
    {
        return $raw ? $this->title : $this->getTitleWithRating();
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getTitleWithRating(): string
    {
        $avg = $this->getAvgRating();
        return '<span class="badge bg-warning align-middle">'.$avg.'</span> '.$this->title;
    }

    public function getAvgRating(): float
    {
        $sum = array_reduce($this->ratings->toArray(), function ($sum, $value ){
            return $sum += $value->getValue();
        });
        return $sum ? (float)($sum / $this->ratings->count())  : 0;
    }

    public function getText(): string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
        }

        return $this;
    }

    public function getDateCreate(): DateTimeInterface
    {
        return $this->date_create;
    }

    public function setDateCreate(DateTimeInterface $date_create): self
    {
        $this->date_create = $date_create;

        return $this;
    }

    public function getDateUpdate(): DateTimeInterface
    {
        return $this->date_update;
    }

    public function setDateUpdate(DateTimeInterface $date_update): self
    {
        $this->date_update = $date_update;

        return $this;
    }

    public function getAuthor(): User
    {
        return $this->author;
    }

    public function setAuthor(User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCategory(): Category
    {
        return $this->category;
    }

    public function setCategory(Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    /**
     * @return Collection|Like[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
        }

        return $this;
    }

    public function removeLike(Like $like): self
    {
        $this->likes->removeElement($like);
        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): ?Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setReview($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        $image->getFms()->imageRemove($image->getSlug());
        $this->images->removeElement($image);

        return $this;
    }

    public function getScore(): int
    {
        return $this->score;
    }

    public function setScore(int $score): self
    {
        $this->score = $score;

        return $this;
    }

    /**
     * @return Collection|Rating[]
     */
    public function getRatings(): Collection
    {
        return $this->ratings;
    }

    public function addRating(Rating $rating): self
    {
        if (!$this->ratings->contains($rating)) {
            $this->ratings[] = $rating;
            $rating->setReview($this);
        }

        return $this;
    }

    public function removeRating(Rating $rating): self
    {
        if ($this->ratings->removeElement($rating)) {
            // set the owning side to null (unless already changed)
            if ($rating->getReview() === $this) {
                $rating->setReview(null);
            }
        }

        return $this;
    }
}

src/Controller/ReviewController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Comment;
use App\Entity\Like;
use App\Entity\Rating;
use App\Entity\Review;
use App\Entity\User;
use App\Form\Type\ImageType;
use App\Form\Type\TagType;
use App\Service\FileManagerService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\RangeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ReviewController extends AbstractController
{
    private EntityManagerInterface $em;
    private FileManagerService $fms;

    public function __construct(EntityManagerInterface $em, FileManagerService $fms)
    {
        $this->em = $em;
        $this->fms = $fms;
    }

    #[Route('{_locale<%app.locales%>}/review/id{reviewId}', name: 'review')]
    public function index($reviewId, Request $request): Response
    {
        $review = $this->em->getRepository(Review::class)->findFullData($reviewId);
        $user = $this->getUser();
        if($this->isGranted('IS_AUTHENTICATED_FULLY'))
        {
            $comment = new Comment($review, $user);
            $comment_form = $this->createFormBuilder($comment)
                ->add('text', TextType::class, ['required' => true, 'label'=> false])
                ->add('save', SubmitType::class, ['label' => 'form.buttons.send'])
                ->getForm();

            $comment_form->handleRequest($request);

            if($comment_form->isSubmitted() && $comment_form->isValid())
            {
                $comment->setText($comment_form->get('text')->getData());
                $review->addComment($comment);
                $this->em->persist($comment);
                $this->em->flush();
                return $this->redirectToRoute('review', ['reviewId' => $reviewId]);
            }

            $rating = $this->em->getRepository(Rating::class)->findOneBy([
                'user' => $this->getUser(),
                'review' => $review
            ]);
            $newObj = false;
            if($rating == null)
            {
                $newObj = true;
                $rating = new Rating($review, $user);
            }
            $rating_form = $this->createFormBuilder($rating)
                ->add('value', RangeType::class, [
                    'attr' => [
                        'min' => 1,
                        'max' => 5
                    ],
                    'label' => 'fields.rating',
                    'data' => $rating->getValue()
                ])
                ->add('save', SubmitType::class, ['label' => 'form.buttons.send'])
                ->getForm();

            $rating_form->handleRequest($request);

            if($rating_form->isSubmitted() && $rating_form->isValid())
            {
                $rating->setValue($rating_form->get('value')->getData());
                if($newObj)
                {
                    $this->em->persist($rating);
                }
                $this->em->flush();
                return $this->redirectToRoute('review', ['reviewId' => $reviewId]);
            }
            return $this->renderForm('review/index.html.twig', [
                'review' => $review,
                'comment_form' => $comment_form,
                'rating_form' => $rating_form
            ]);
        }
        return $this->render('review/index.html.twig', [
            'review' => $review,
        ]);
    }

    #[Route('{_locale<%app.locales%>}/review/id{reviewId}/like', name: 'review_like')]
    public function likeAction($reviewId, Request $request): Response
    {
        $review = $this->em->getRepository(Review::class)->find($reviewId);
        $user = $this->getUser();
        $likeFind = $this->em->getRepository(Like::class)->findOneBy([
            'user' => $this->getUser(),
            'review' => $review
        ]);
        if($likeFind) {
            $this->em->remove($likeFind);
            $review->removeLike($likeFind);
        }
        else
        {
            $like = new Like($user, $review);
            $this->em->persist($like);
            $review->addLike($like);
        }
        $this->em->flush();
        return $this->redirectToRoute('review', ['reviewId' => $reviewId]);
    }

    public function createFormReview(Review $review, $isNew = false) : FormInterface
    {
        return $this->createFormBuilder($review)
            ->add('title', TextType::class, [
                'required' => true,
                'label' => 'fields.title',
                'data' => $isNew ? null : $review->getTitle(true)
            ])
            ->add('text', TextareaType::class, [
                'required' => true,
                'label' => 'fields.text',
            ])
            ->add('tags', TagType::class, [
                'required'=> true,
                'label' => 'fields.tags',
            ])
            ->add('images', ImageType::class, [
                'multiple' => true,
                'required' => false,
                'attr' => [
                    'data-controller' => 'mydropzone',
                    'multiple' => 'multiple'
                ],
                'label' => 'fields.images',
            ])
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'name',
                'label' => 'fields.category',
            ])
            ->add('score', RangeType::class, [
                'required'=> true,
                'attr' => [
                    'min' => 1,
                    'max' => 10
                ],
                'label' => 'fields.score',
            ])
            ->add('save', SubmitType::class, ['label' => 'form.buttons.send'])
            ->getForm();
    }

    #[Route('{_locale<%app.locales%>}/review/create/admin/{id}', name: 'create_review_by_admin')]
    public function createReviewByAdmin($id, Request $request): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        $user = $this->em->getRepository(User::class)->find($id);
        if($user == null)
        {
            return $this->redirectToRoute('home_page');
        }
        $review = new Review();
        $form = $this->createFormReview($review, true);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $review = $form->getData();
            $review->setAuthor($user);
            $this->em->persist($review);
            $this->em->flush();
            $this->addFlash('success', 'Обзор добавлен');
            return $this->redirectToRoute('home_page');
        }
        return $this->renderForm('review/createReview.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('{_locale<%app.locales%>}/review/create', name: 'create_review')]
    public function createReview(Request $request): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $review = new Review();
        $form = $this->createFormReview($review, true);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $review = $form->getData();
            $review->setAuthor($this->getUser());
            $this->em->persist($review);
            $this->em->flush();
            $this->addFlash('success', 'Обзор добавлен');
            return $this->redirectToRoute('home_page'); //success add
        }
        return $this->renderForm('review/createReview.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('{_locale<%app.locales%>}/review/id{reviewId}/edit', name: 'edit_review')]
    public function editReview($reviewId, Request $request): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $review = $this->em->getRepository(Review::class)->find($reviewId);
        /**
         * @var User $author
         */
        $author = $review->getAuthor();
        if($author->getId() != $this->getUser()->getId() && !$this->isGranted('ROLE_ADMIN'))
        {
            return $this->redirectToRoute('home_page');
        }
        else
        {
            $form = $this->createFormReview($review);
            $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid())
            {
                $images = $form->get('images')->getData();
                foreach ($images as $image) {
                    $review->addImage($image);
                }
                /**@var $review Review*/
                $review = $form->getData();
                $review->setDateUpdate(new \DateTime());
                $this->addFlash('success', 'Обзор изменен');
                $this->em->flush();

                return $this->redirectToRoute('user_page', ['id' => $author->getId()]); //success add
            }
            return $this->renderForm('review/editReview.html.twig', [
                'form' => $form,
            ]);
        }
    }
    #[Route('{_locale<%app.locales%>}/review/id{reviewId}/delete', name: 'delete_review')]
    public function deleteReview($reviewId, Request $request): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $review = $this->em->getRepository(Review::class)->find($reviewId);
        /**
         * @var User $author
         */
        $author = $review->getAuthor();
        if($author->getId() != $this->getUser()->getId() && !$this->isGranted('ROLE_ADMIN'))
        {
            return $this->redirectToRoute('home_page');
        }
        else
        {
            $this->em->remove($review);

templates/review/createReview.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'main.create_review'|trans }}{% endblock %}

{% block body %}
    <div class="w-75">
        {{ form_start(form) }}
        {{ form_row(form.title) }}
        {{ form_row(form.text) }}
        {{ form_label(form.images) }}
        {{form_widget(form.images, { 'multiple': true , 'attr': {'multiple': 'multiple'} })}}
        {{ form_rest(form) }}
        {{ form_end(form) }}
    </div>
{% endblock %}

{% block javascripts_after %}
<script>
  let split = function( val ) {
    return val.split(",").map((el)=>el.trim());
  };

  $(document).ready(function () {
    $('#form_tags').autocomplete({
      source: "{{ path('tag_autocomplete') }}",
      minLength: 2,
      focus: function() {
        return false;
      },
      select: function( event, ui ) {
        let terms = split( this.value );
        terms.pop();
        terms.push(ui.item.value.trim());
        this.value = terms.join(", ");
        return false;
      }
    });
  })


</script>

{% endblock %}

templates/review/editReview.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit review!{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div class="example-wrapper">
        {{ form_start(form) }}
            {{ form_row(form.title) }}
            {{ form_row(form.text) }}
            {{ form_label(form.images) }}
            {{form_widget(form.images, { 'multiple': true , 'attr': {'multiple': 'multiple'} })}}
            {{ form_rest(form) }}
        {{ form_end(form) }}
    </div>
{% endblock %}

{% block javascripts_after %}
<script>
  let split = function( val ) {
    return val.split(",").map((el)=>el.trim());
  };

  $(document).ready(function () {
    $('#form_tags').autocomplete({
      source: "{{ path('tag_autocomplete') }}",
      minLength: 2,
      focus: function() {
        return false;
      },
      select: function( event, ui ) {
        let terms = split( this.value );
        terms.pop();
        terms.push(ui.item.value.trim());
        this.value = terms.join(", ");
        return false;
      }
    });
  })


</script>

{% endblock %}

templates/review/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Review | {{review.getTitle(true)}}!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>{{review.title|raw}}!</h1>
    <p class="lead">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
            <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
        </svg>
        <span class="h6"><a href="{{ path('user_page', {'id': review.author.id}) }}">{{ review.author.getFullName()|raw }}</a></span>
    </p>
    <h5>{{'fields.category'|trans}}: <strong>{{ review.category.name }}</strong></h5>
    <p>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-tags" viewBox="0 0 16 16">
            <path d="M3 2v4.586l7 7L14.586 9l-7-7H3zM2 2a1 1 0 0 1 1-1h4.586a1 1 0 0 1 .707.293l7 7a1 1 0 0 1 0 1.414l-4.586 4.586a1 1 0 0 1-1.414 0l-7-7A1 1 0 0 1 2 6.586V2z"/>
            <path d="M5.5 5a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1zm0 1a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3zM1 7.086a1 1 0 0 0 .293.707L8.75 15.25l-.043.043a1 1 0 0 1-1.414 0l-7-7A1 1 0 0 1 0 7.586V3a1 1 0 0 1 1-1v5.086z"/>
        </svg>
        {{'fields.tags'|trans}}:
        {% for tag in review.tags %}
            <span class="badge badge-info">{{ tag.name }}</span>
        {% endfor %}
    </p>
    <div class="rounded p-2 block-text text-center" style="background-color: #ddd; min-height: 300px;">
        {{review.text|markdown}}
    </div>
    {% for image in review.images %}
        <img alt src="{{ image.sharedUri }}" style="height: 100px;">
    {% endfor %}
    <p class="h5">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-half" viewBox="0 0 16 16">
            <path d="M5.354 5.119 7.538.792A.516.516 0 0 1 8 .5c.183 0 .366.097.465.292l2.184 4.327 4.898.696A.537.537 0 0 1 16 6.32a.548.548 0 0 1-.17.445l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256a.52.52 0 0 1-.146.05c-.342.06-.668-.254-.6-.642l.83-4.73L.173 6.765a.55.55 0 0 1-.172-.403.58.58 0 0 1 .085-.302.513.513 0 0 1 .37-.245l4.898-.696zM8 12.027a.5.5 0 0 1 .232.056l3.686 1.894-.694-3.957a.565.565 0 0 1 .162-.505l2.907-2.77-4.052-.576a.525.525 0 0 1-.393-.288L8.001 2.223 8 2.226v9.8z"/>
        </svg>
        {{ 'fields.score'|trans }}: {{ review.score }}
    </p>
    <p class="h5">{{ 'fields.likes'|trans }}: {{ review.likes|length }}
    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
        <a class="btn btn-outline-danger align-middle" href="{{ path('review_like', {'reviewId': review.id}) }}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up" viewBox="0 0 16 16">
                <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.144 2.144 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a9.84 9.84 0 0 0-.443.05 9.365 9.365 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111L8.864.046zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a8.908 8.908 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.224 2.224 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.866.866 0 0 1-.121.416c-.165.288-.503.56-1.066.56z"/>
            </svg>
        </a>

    {% endif %}
    </p>
    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
        {{ form(rating_form) }}
    {% endif %}
    <p class="h5">{{ 'fields.comments'|trans }}: </p>
    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
        {{ form(comment_form) }}
        {% for comment in review.comments %}
            <figure class="border border-success rounded p-2">
                <blockquote class="blockquote">
                    <p class="h6">{{comment.text}}</p>
                </blockquote>
                <figcaption class="blockquote-footer">
                    {{ comment.user.getFullName()|raw }} {{ 'word.in'|trans }} <cite title="Source Title">{{comment.dateCreate|date("H:i d.m")}}</cite>
                </figcaption>
            </figure>
        {% endfor %}
    {% else %}
        <p>{{ 'review.comments.not_available'|trans }}</p>
    {% endif %}
</div>
{% endblock %}